### ISSUE TITLE
Select-ColorString Context Support

### ISSUE THREAD

**Issue by ShawnNeckelmann** [copdips/PSScripts#1]
In the Select-ColorString, would it be possible to support the [Context](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.1#example-8--find-lines-before-and-after-a-match) parameter?

**Comment by copdips** [comment]
hi @ShawnNeckelmann 
Sorry, it's not possible in `Select-ColorString`, and Powershell 7 has embedded the highlighting by default. I suggest you to use the original `Select-String`, it has all the params. `Select-ColorString` is more or less considered as deprecated.

https://copdips.com/2018/05/grep-like-powershell-colorful-select-string.html#update-2019-12-28-powershell-7-select-string-default-highlighting

**Comment by ShawnNeckelmann** [comment]
Thank you @copdips .  I'm new to this usage of PowerShell so am unfamiliar.  I appreciate your suggestions.
